import pandas as pd

map_synop = {
    "BIA YSTOK": "BIALYSTOK",
    "BIELSKO-BIA A": "BIELSKO-BIALA",
    "BYDGOSZCZ": "BYDGOSZCZ",
    "CHOJNICE": "CHOJNICE",
    "CZ STOCHOWA": "CZESTOCHOWA",
    "ELBL G-MILEJEWO": "ELBLAG-MILEJEWO",
    "GDA SK-PORT PÓ NOCNY": "GDANSK-PORT POLNOCNY",
    "GDA SK-R BIECHOWO": "GDANSK-REBIECHOWO",
    "GDA SK-WIBNO": "GDANSK-SWIBNO",
    "GORZ�W WIELKOPOLSKI": "GORZOW WIELKOPOLSKI",
    "HALA G SIENICOWA": "HALA GASIENICOWA",
    "HEL": "HEL",
    "JELENIA G�RA": "JELENIA GORA",
    "KALISZ": "KALISZ",
    "KASPROWY WIERCH": "KASPROWY WIERCH",
    "KATOWICE-MUCHOWIEC": "KATOWICE-MUCHOWIEC",
    "K TRZYN": "KETRZYN",
    "KIELCE-SUK�W": "KIELCE-SUKOW",
    "K ODZKO": "KLODZKO",
    "KO O": "KOLO",
    "KO OBRZEG-DWIRZYNO": "KOLOBRZEG-DZWIRZYNO",
    "KOSZALIN": "KOSZALIN",
    "KOZIENICE": "KOZIENICE",
    "KRAKÓW-BALICE": "KRAKOW-BALICE",
    "KROSNO": "KROSNO",
    "LEGNICA": "LEGNICA",
    "LESKO": "LESKO",
    "LESZNO": "LESZNO",
    "L BORK": "LEBORK",
    "LUBLIN-RADAWIEC": "LUBLIN-RADAWIEC",
    "EBA": "LEBA",
    "ÓD-LUBLINEK": "LODZ-LUBLINEK",
    "MIKO AJKI": "MIKOLAJKI",
    "M AWA": "MLAWA",
    "NOWY S CZ": "NOWY SACZ",
    "OLSZTYN": "OLSZTYN",
    "OPOLE": "OPOLE",
    "OSTRO KA": "OSTROLEKA",
    "PI A": "PILA",
    "P OCK": "PLOCK",
    "POZNA - AWICA": "POZNAN-LAWICA",
    "PRZEMYL": "PRZEMYSL",
    "RACIBÓRZ": "RACIBORZ",
    "RESKO-SM�LSKO": "RESKO-SMOLDZINO",
    "RZESZ�W-JASIONKA": "RZESZOW-JASIONKA",
    "SANDOMIERZ": "SANDOMIERZ",
    "SIEDLCE": "SIEDLCE",
    "S UBICE": "SLUBICE",
    "SULEJ�W": "SULEJOW",
    "SUWA KI": "SUWALKI",
    "SZCZECIN": "SZCZECIN",
    "SZCZECINEK": "SZCZECINEK",
    "NIE KA": "SNIEZKA",
    "WINOUJCIE": "SWINOUJSCIE",
    "TARNÓW": "TARNOW",
    "TERESPOL": "TERESPOL",
    "TORU ": "TORUN",
    "USTKA": "USTKA",
    "WARSZAWA-OK CIE": "WARSZAWA-OKECIE",
    "WIELU ": "WIELUN",
    "W ODAWA": "WLODAWA",
    "WROC AW-STRACHOWICE": "WROCLAW-STRACHOWICE",
    "ZAKOPANE": "ZAKOPANE",
    "ZAMO": "ZAMOSC",
    "ZGORZELEC": "ZGORZELEC",
    "ZIELONA G�RA": "ZIELONA GORA",
    "ARNOWIEC": "ZARNOWIEC"
}

"""
map_klimat = {
    "BIA YSTOK": "BIAŁYSTOK",
    "BIELSKO-BIA A": "BIELSKO-BIAŁA",
    "CZ STOCHOWA": "CZĘSTOCHOWA",
    "ELBL G-MILEJEWO": "ELBLĄG-MILEJEWO",
    "GDA SK-PORT PÓ NOCNY": "GDAŃSK-PORT PÓŁNOCNY",
    "GDA SK-R BIECHOWO": "GDAŃSK-RĘBIECHOWO",
    "GDA SK-ŚWIBNO": "GDAŃSK-ŚWIBNO",
    "HALA G SIENICOWA": "HALA GĄSIENICOWA",
    "K TRZYN": "KĘTRZYN",
    "K ODZKO": "KŁODZKO",
    "KO O": "KOŁO",
    "KO OBRZEG-DŹWIRZYNO": "KOŁOBRZEG-DŹWIRZYNO",
    "L BORK": "LĘBORK",
    "EBA": "ŁEBA",
    "ÓDŹ-LUBLINEK": "ŁÓDŹ-LUBLINEK",
    "MIKO AJKI": "MIKOŁAJKI",
    "M AWA": "MŁAWA",
    "NOWY S CZ": "NOWY SĄCZ",
    "OSTRO KA": "OSTROŁĘKA",
    "PI A": "PIŁA",
    "P OCK": "PŁOCK",
    "POZNA - AWICA": "POZNAŃ-ŁAWICA",
    "RESKO-SMÓLSKO": "RESKO-SMOŁDZINO",
    "RZESZÓW-JASIONKA": "RZESZÓW-JASIONKA",
    "S UBICE": "SŁUBICE",
    "SUWA KI": "SUWAŁKI",
    "ŚNIE KA": "ŚNIEŻKA",
    "ŚWINOUJŚCIE": "ŚWINOUJŚCIE",
    "WARSZAWA-OK CIE": "WARSZAWA-OKĘCIE",
    "W ODAWA": "WŁODAWA",
    "WROC AW-STRACHOWICE": "WROCŁAW-STRACHOWICE",
    "ZAMOŚ": "ZAMOŚĆ",
    "ZIELONA GÓRA": "ZIELONA GÓRA",
    "ARNOWIEC": "ŻARNOWIEC",
    "BALIGRÓD-MCHAWA": "BALIGRÓD-MCHAWA",
    "BE CHATÓW": "BEŁCHATÓW",
    "BIA A PODLASKA": "BIAŁA PODLASKA",
    "BIA OGARD": "BIAŁOGARD",
    "BIA OWIE A": "BIAŁOWIEŻA",
    "BIEBRZA-PIE CZYKÓWEK": "BIEBRZA-PIECZYKÓWEK",
    "BIELSK PODLASKI": "BIELSK PODLASKI",
    "BIERU STARY": "BIERUŃ STARY",
    "BOGUS AWICE": "BOGUSŁAWICE",
    "BOLES AWÓW": "BOLESŁAWÓW",
    "BUKOWINA TATRZA SKA": "BUKOWINA TATRZAŃSKA",
    "CEBER": "CĘBER",
    "CHWA KOWICE": "CHWAŁKOWICE",
    "CICIBÓR": "CICIBÓR",
    "CZARNA D BRÓWKA": "CZARNA DĄBRÓWKA",
    "CZEKANÓW": "CZĘKANÓW",
    "CZORSZTYN-NADZAMCZE": "CZORSZTYN-NADZAMCZE",
    "DAR OWO": "DARŁOWO",
    "D BNO": "DĘBNO",
    "D UGOPOLE-ZDRÓJ": "DŁUGOPOLE-ZDRÓJ",
    "G ODOWO": "GŁODOWO",
    "G UBCZYCE": "GŁUBCZYCE",
    "G UCHO AZY": "GŁUCHOŁAZY",
    "GO DAP": "GOŁDAP",
    "GRUDZI DZ": "GRUDZIĄDZ",
    "GUBA ÓWKA": "GUBAŁÓWKA",
    "HOPOWO": "CHOPOWO",
    "IGO OMIA": "IGŁOMIA",
    "INWA D": "INWAŁD",
    "JAB ONKA": "JABŁONKA",
    "JARCZEW": "JARCZEW",
    "JASTRZ BIA": "JASTRZĘBIA",
    "JASTRZ BIE-ZDRÓJ": "JASTRZĘBIE-ZDRÓJ",
    "J DĘDZEJÓW-SUDÓW": "JĘDZEJÓW-SUDÓW",
    "KAW CZYN": "KAŁCZYN",
    "K ODZKO": "KŁODZKO",
    "KO UDA WIELKA": "KOŁUDA WIELKA",
    "KOMA CZA": "KOMAŃCZA",
    "KOSZALIN": "KOSZALIN",
    "KÓRNIK": "KÓRNIK",
    "LE AJSK": "LEŻAJSK",
    "LIBERTÓW": "LIBERTÓW",
    "LIMANOWA": "LIMANOWA",
    "LU MIERZ": "ŁUBNICA",
    "AZISKA": "ŁAZISKA",
    "AZY": "ŁAZY",
    "MAKÓW PODHALA SKI": "MAKÓW PODHALAŃSKI",
    "MI DZYBRODZIE BIALSKIE": "MIĘDZYBRODZIE BIALSKIE",
    "MIZERNA": "MIZERNA",
    "M AWA": "MŁAWA",
    "MUSZYNA": "MUSZYNA",
    "NAMYS ÓW": "NAMYSŁÓW",
    "NOWA WIEŚ": "NOWA WIEŚ",
    "OBIDOWA": "OBIDOWA",
    "PIWNICZNA": "PIWNICZNA",
    "PIWNICZNA": "PIWNICZNA",
    "PORONIN": "PORONIN",
    "PSZCZYNA": "PSZCZYNA",
    "RADOSTOWO": "RADOSTOWO",
    "STASZÓW": "STASZÓW",
    "SZKLARSKA POR BA": "SZKLARSKA PORĘBA",
    "SZPROTAWA": "SZPROTAWA",
    "ŚNIE KA": "ŚNIEŻKA",
    "TARNOGRÓD": "TARNOGRÓD",
    "TERESPOL": "TERESPOL",
    "USTKA": "USTKA",
    "WARSZAWA-BIELANY": "WARSZAWA-BIELANY",
    "WERBKOWICE": "WERBKOWICE",
    "WI SKO": "WIŚLISKO",
    "ZGORZELEC": "ZGORZELEC",
    "ZGORZELEC": "ZGORZELEC",
    "ZIELONA GÓRA": "ZIELONA GÓRA",
    "ŻYBISZÓW": "ŻYBISZÓW",
    "ARNOWA": "ŻARNOWA",
    "UBRACZE": "ŻUBRACZE"
}
"""

file_path_synop = 'data/stacje_synop.csv'
file_path_klimat = 'data/stacje_klimat.csv'

stacje_synop = pd.read_csv(file_path_synop, delimiter=";", encoding='ISO-8859-2', engine='python')
stacje_klimat = pd.read_csv(file_path_klimat, delimiter=";", encoding='ISO-8859-2', engine='python')

stacje_synop['szerokosc_geo'] = stacje_synop['dlugosc_stopnie'] + (stacje_synop['dlugosc_minuty'] / 60) + (stacje_synop['dlugosc_sekundy'] / 3600)
stacje_synop['dlugosc_geo'] = stacje_synop['szerokosc_stopnie'] + (stacje_synop['szerokosc_minuty'] / 60) + (stacje_synop['szerokosc_sekundy'] / 3600)

stacje_klimat['szerokosc_geo'] = stacje_klimat['dlugosc_stopnie'] + (stacje_klimat['dlugosc_minuty'] / 60) + (stacje_klimat['dlugosc_sekundy'] / 3600)
stacje_klimat['dlugosc_geo'] = stacje_klimat['szerokosc_stopnie'] + (stacje_klimat['szerokosc_minuty'] / 60) + (stacje_klimat['szerokosc_sekundy'] / 3600)

stacje_synop['nazwa_stacji'] = stacje_synop['nazwa_stacji'].replace(map_synop)
# stacje_klimat['nazwa_stacji'] = stacje_synop['nazwa_stacji'].replace(map_klimat)

stacje_synop_cleaned = stacje_synop.drop(columns=['szerokosc_stopnie', 'szerokosc_minuty', 'szerokosc_sekundy', 'dlugosc_stopnie', 'dlugosc_minuty', 'dlugosc_sekundy'])
stacje_klimat_cleaned = stacje_klimat.drop(columns=['szerokosc_stopnie', 'szerokosc_minuty', 'szerokosc_sekundy', 'dlugosc_stopnie', 'dlugosc_minuty', 'dlugosc_sekundy', 'Unnamed: 8'])

output_path_synop = 'data/stacje_synop_converted.csv'
output_path_klimat = 'data/stacje_klimat_converted.csv'
stacje_synop_cleaned.to_csv(output_path_synop, sep=',', index=False)
stacje_klimat_cleaned.to_csv(output_path_klimat, sep=',', index=False)
